import { SmiskiSeries } from "@/lib";

export const SMISKI_DATA: SmiskiSeries = {
  "Series 1": [
    { name: "Hiding", isSecret: false },
    { name: "Hugging Knees", isSecret: false },
    { name: "Looking Back", isSecret: false },
    { name: "Lounging", isSecret: false },
    { name: "Peeking", isSecret: false },
    { name: "Sitting", isSecret: false },
    { name: "Little Lifting", isSecret: false },
    { name: "Little Peeking", isSecret: false },
    { name: "Little Hugging", isSecret: false },
    { name: "The Scream", isSecret: true },
    { name: "Rudolph", isSecret: true },
  ],
  "Series 2": [
    { name: "Climbing", isSecret: false },
    { name: "Daydreaming", isSecret: false },
    { name: "Kneeling", isSecret: false },
    { name: "Listening", isSecret: false },
    { name: "Peeking", isSecret: false },
    { name: "Pushing", isSecret: false },
    { name: "Venus", isSecret: true },
    { name: "Snowman", isSecret: true },
  ],
  "Series 3": [
    { name: "Bridge", isSecret: false },
    { name: "Climbing", isSecret: false },
    { name: "Handstand", isSecret: false },
    { name: "Hiding", isSecret: false },
    { name: "Little", isSecret: false },
    { name: "Peeking", isSecret: false },
    { name: "The Thinker", isSecret: true },
  ],
  "Series 4": [
    { name: "Defeated", isSecret: false },
    { name: "Lazy", isSecret: false },
    { name: "Relaxing", isSecret: false },
    { name: "Scared", isSecret: false },
    { name: "Sneaking", isSecret: false },
    { name: "Stuck", isSecret: false },
    { name: "Twin Angels", isSecret: true },
  ],
  Toilet: [
    { name: "Helping Out", isSecret: false },
    { name: "Holding In", isSecret: false },
    { name: "Little (Smelly)", isSecret: false },
    { name: "Peek-A-Boo", isSecret: false },
    { name: "Resting", isSecret: false },
    { name: "Squatting", isSecret: false },
    { name: "Water Fountain", isSecret: true },
  ],
  Bath: [
    { name: "Dazed", isSecret: false },
    { name: "Looking", isSecret: false },
    { name: "Not Looking", isSecret: false },
    { name: "Scrubbing", isSecret: false },
    { name: "Shampooing", isSecret: false },
    { name: "With Duck", isSecret: false },
    { name: "Water Droplet", isSecret: true },
  ],
  Living: [
    { name: "Daydreaming", isSecret: false },
    { name: "Hiding", isSecret: false },
    { name: "Lifting", isSecret: false },
    { name: "Nap Time", isSecret: false },
    { name: "Playing", isSecret: false },
    { name: "Thinking", isSecret: false },
    { name: "Sunflower", isSecret: true },
  ],
  Bed: [
    { name: "At Sleep", isSecret: false },
    { name: "Before Rest", isSecret: false },
    { name: "Co-Sleeping", isSecret: false },
    { name: "Fussing", isSecret: false },
    { name: "Reading", isSecret: false },
    { name: "Sleepy", isSecret: false },
    { name: "Crescent Moon", isSecret: true },
  ],
  Yoga: [
    { name: "Lotus Pose", isSecret: false },
    { name: "Ship Pose", isSecret: false },
    { name: "Shouldstand Pose", isSecret: false },
    { name: "Tree Pose", isSecret: false },
    { name: "Triangle Pose", isSecret: false },
    { name: "Twist Pose", isSecret: false },
    { name: "Twin Hearts", isSecret: true },
  ],
  Cheer: [
    { name: "Little Cheerleading", isSecret: false },
    { name: "Cheering", isSecret: false },
    { name: "Dancing", isSecret: false },
    { name: "Marching", isSecret: false },
    { name: "On Drums", isSecret: false },
    { name: "On Your Side", isSecret: false },
    { name: "Trophy Angel", isSecret: true },
  ],
  Museum: [
    { name: "Bacchus", isSecret: false },
    { name: "Dali", isSecret: false },
    { name: "Fuzin & Raijin", isSecret: false },
    { name: "Pearl Earring", isSecret: false },
    { name: "The Source", isSecret: false },
    { name: "Velazquez", isSecret: false },
    { name: "King Tut", isSecret: true },
  ],
  "@Work": [
    { name: "Little Group Think", isSecret: false },
    { name: "Approving", isSecret: false },
    { name: "Good Idea", isSecret: false },
    { name: "On The Road", isSecret: false },
    { name: "Presenting", isSecret: false },
    { name: "Researching", isSecret: false },
    { name: "Lucky Cat", isSecret: true },
  ],
  Dressing: [
    { name: "Loose Pants", isSecret: false },
    { name: "Putting On Socks", isSecret: false },
    { name: "Struggling", isSecret: false },
    { name: "Sweater", isSecret: false },
    { name: "Tight Pants", isSecret: false },
    { name: "Underpants", isSecret: false },
    { name: "Costume Bunny", isSecret: true },
  ],
  Exercising: [
    { name: "Little Balance", isSecret: false },
    { name: "Aerobics", isSecret: false },
    { name: "Doing Crunches", isSecret: false },
    { name: "Dumbbell", isSecret: false },
    { name: "Hoop", isSecret: false },
    { name: "Stretch", isSecret: false },
    { name: "Flexing", isSecret: true },
  ],
  Moving: [
    { name: "Green Thumb", isSecret: false },
    { name: "Little Teamwork", isSecret: false },
    { name: "Balancing Boxes", isSecret: false },
    { name: "Carrying Ladder", isSecret: false },
    { name: "Decorating", isSecret: false },
    { name: "Falling Down", isSecret: false },
    { name: "Teddy", isSecret: true },
  ],
  Sunday: [
    { name: "Blowing Bubbles", isSecret: false },
    { name: "Gardening", isSecret: false },
    { name: "Paper Airplane", isSecret: false },
    { name: "Sing-Along", isSecret: false },
    { name: "Skateboarding", isSecret: false },
    { name: "Sunbathing", isSecret: false },
    { name: "Dog Walk", isSecret: true },
  ],
  Hippers: [
    { name: "Smartphone", isSecret: false },
    { name: "Climbing", isSecret: false },
    { name: "Looking Out", isSecret: false },
    { name: "Sticking", isSecret: false },
    { name: "Dozing", isSecret: false },
    { name: "Upside Down", isSecret: false },
    { name: "Headphones", isSecret: true },
  ],
};

export const SERIES_COLORS: Record<string, string> = {
  "Series 1": "bg-[#78c328]/50 border-[#78c328]",
  "Series 2": "bg-[#ee7e00]/50 border-[#ee7e00]",
  "Series 3": "bg-[#8b65c3]/50 border-[#8b65c3]",
  "Series 4": "bg-[#da4b8e]/50 border-[#da4b8e]",
  Toilet: "bg-[#52b782]/50 border-[#52b782]",
  Bath: "bg-[#20b8c5]/50 border-[#20b8c5]",
  Living: "bg-[#f08d74]/50 border-[#f08d74]",
  Bed: "bg-[#6879ba]/50 border-[#6879ba]",
  Yoga: "bg-[#ff6633]/50 border-[#ff6633]",
  Cheer: "bg-[#ea5a94]/50 border-[#ea5a94]",
  Museum: "bg-[#e40012]/50 border-[#e40012]",
  "@Work": "bg-[#00a143]/50 border-[#00a143]",
  Dressing: "bg-[#f5a100]/50 border-[#f5a100]",
  Exercising: "bg-[#e15e76]/50 border-[#e15e76]",
  Moving: "bg-[#e40012]/50 border-[#e40012]",
  Sunday: "bg-[#c94d97]/50 border-[#c94d97]",
  Hippers: "bg-[#ffd700]/30 border-[#ffd700]/80",
};
