import { SmiskiSeries } from "@/lib";

export const SMISKI_DATA: SmiskiSeries = {
  "Series 1": [
    { name: "Hiding", isSecret: false },
    { name: "Hugging Knees", isSecret: false },
    { name: "Looking Back", isSecret: false },
    { name: "Lounging", isSecret: false },
    { name: "Peeking", isSecret: false },
    { name: "Sitting", isSecret: false },
    { name: "Little Lifting", isSecret: false },
    { name: "Little Peeking", isSecret: false },
    { name: "Little Hugging", isSecret: false },
    { name: "The Scream", isSecret: true },
    { name: "Rudolph", isSecret: true },
  ],
  "Series 2": [
    { name: "Climbing", isSecret: false },
    { name: "Daydreaming", isSecret: false },
    { name: "Kneeling", isSecret: false },
    { name: "Listening", isSecret: false },
    { name: "Peeking", isSecret: false },
    { name: "Pushing", isSecret: false },
    { name: "Venus", isSecret: true },
    { name: "Snowman", isSecret: true },
  ],
  "Series 3": [
    { name: "Bridge", isSecret: false },
    { name: "Climbing", isSecret: false },
    { name: "Handstand", isSecret: false },
    { name: "Hiding", isSecret: false },
    { name: "Little", isSecret: false },
    { name: "Peeking", isSecret: false },
    { name: "The Thinker", isSecret: true },
  ],
  "Series 4": [
    { name: "Defeated", isSecret: false },
    { name: "Lazy", isSecret: false },
    { name: "Relaxing", isSecret: false },
    { name: "Scared", isSecret: false },
    { name: "Sneaking", isSecret: false },
    { name: "Stuck", isSecret: false },
    { name: "Twin Angels", isSecret: true },
  ],
  Toilet: [
    { name: "Helping Out", isSecret: false },
    { name: "Holding In", isSecret: false },
    { name: "Little (Smelly)", isSecret: false },
    { name: "Peek-A-Boo", isSecret: false },
    { name: "Resting", isSecret: false },
    { name: "Squatting", isSecret: false },
    { name: "Water Fountain", isSecret: true },
  ],
  Bath: [
    { name: "Dazed", isSecret: false },
    { name: "Looking", isSecret: false },
    { name: "Not Looking", isSecret: false },
    { name: "Scrubbing", isSecret: false },
    { name: "Shampooing", isSecret: false },
    { name: "With Duck", isSecret: false },
    { name: "Water Droplet", isSecret: true },
  ],
  Living: [
    { name: "Daydreaming", isSecret: false },
    { name: "Hiding", isSecret: false },
    { name: "Lifting", isSecret: false },
    { name: "Nap Time", isSecret: false },
    { name: "Playing", isSecret: false },
    { name: "Thinking", isSecret: false },
    { name: "Sunflower", isSecret: true },
  ],
  Bed: [
    { name: "At Sleep", isSecret: false },
    { name: "Before Rest", isSecret: false },
    { name: "Co-Sleeping", isSecret: false },
    { name: "Fussing", isSecret: false },
    { name: "Reading", isSecret: false },
    { name: "Sleepy", isSecret: false },
    { name: "Crescent Moon", isSecret: true },
  ],
  Yoga: [
    { name: "Lotus Pose", isSecret: false },
    { name: "Ship Pose", isSecret: false },
    { name: "Shouldstand Pose", isSecret: false },
    { name: "Tree Pose", isSecret: false },
    { name: "Triangle Pose", isSecret: false },
    { name: "Twist Pose", isSecret: false },
    { name: "Twin Hearts", isSecret: true },
  ],
  Cheer: [
    { name: "Little Cheerleading", isSecret: false },
    { name: "Cheering", isSecret: false },
    { name: "Dancing", isSecret: false },
    { name: "Marching", isSecret: false },
    { name: "On Drums", isSecret: false },
    { name: "On Your Side", isSecret: false },
    { name: "Trophy Angel", isSecret: true },
  ],
  Museum: [
    { name: "Bacchus", isSecret: false },
    { name: "Dali", isSecret: false },
    { name: "Fuzin & Raijin", isSecret: false },
    { name: "Pearl Earring", isSecret: false },
    { name: "The Source", isSecret: false },
    { name: "Velazquez", isSecret: false },
    { name: "King Tut", isSecret: true },
  ],
  "@Work": [
    { name: "Little Group Think", isSecret: false },
    { name: "Approving", isSecret: false },
    { name: "Good Idea", isSecret: false },
    { name: "On The Road", isSecret: false },
    { name: "Presenting", isSecret: false },
    { name: "Researching", isSecret: false },
    { name: "Lucky Cat", isSecret: true },
  ],
  Dressing: [
    { name: "Loose Pants", isSecret: false },
    { name: "Putting On Socks", isSecret: false },
    { name: "Struggling", isSecret: false },
    { name: "Sweater", isSecret: false },
    { name: "Tight Pants", isSecret: false },
    { name: "Underpants", isSecret: false },
    { name: "Costume Bunny", isSecret: true },
  ],
  Exercising: [
    { name: "Little Balance", isSecret: false },
    { name: "Aerobics", isSecret: false },
    { name: "Doing Crunches", isSecret: false },
    { name: "Dumbbell", isSecret: false },
    { name: "Hoop", isSecret: false },
    { name: "Stretch", isSecret: false },
    { name: "Flexing", isSecret: true },
  ],
  Moving: [
    { name: "Green Thumb", isSecret: false },
    { name: "Little Teamwork", isSecret: false },
    { name: "Balancing Boxes", isSecret: false },
    { name: "Carrying Ladder", isSecret: false },
    { name: "Decorating", isSecret: false },
    { name: "Falling Down", isSecret: false },
    { name: "Teddy", isSecret: true },
  ],
  Sunday: [
    { name: "Blowing Bubbles", isSecret: false },
    { name: "Gardening", isSecret: false },
    { name: "Paper Airplane", isSecret: false },
    { name: "Sing-Along", isSecret: false },
    { name: "Skateboarding", isSecret: false },
    { name: "Sunbathing", isSecret: false },
    { name: "Dog Walk", isSecret: true },
  ],
  Birthday: [
    { name: "Giving a Bouquet", isSecret: false },
    { name: "Wrapped Up", isSecret: false },
    { name: "Popping Confetti", isSecret: false },
    { name: "Birthday Message", isSecret: false },
    { name: "Little Decorating", isSecret: false },
    { name: "Tasting", isSecret: false },
    { name: "Candle", isSecret: true },
  ],
  Construction: [
    { name: "Digging a Hole", isSecret: false },
    { name: "Crushing Rock", isSecret: false },
    { name: "Tightening Bolt", isSecret: false },
    { name: "Measuring", isSecret: false },
    { name: "Directing Traffic", isSecret: false },
    { name: "Loosening Bolt", isSecret: false },
    { name: "Roadblock", isSecret: true },
  ],
  Hippers: [
    { name: "Smartphone", isSecret: false },
    { name: "Climbing", isSecret: false },
    { name: "Looking Out", isSecret: false },
    { name: "Sticking", isSecret: false },
    { name: "Dozing", isSecret: false },
    { name: "Upside Down", isSecret: false },
    { name: "Headphones", isSecret: true },
  ],
};

export const DISCONTINUED_SERIES = ["Series 2", "Series 3", "Series 4"];

export const SERIES_COLORS: Record<string, string> = {
  "Series 1": "series-series-1",
  "Series 2": "series-series-2",
  "Series 3": "series-series-3",
  "Series 4": "series-series-4",
  Toilet: "series-toilet",
  Bath: "series-bath",
  Living: "series-living",
  Bed: "series-bed",
  Yoga: "series-yoga",
  Cheer: "series-cheer",
  Museum: "series-museum",
  "@Work": "series-at-work",
  Dressing: "series-dressing",
  Exercising: "series-exercising",
  Moving: "series-moving",
  Sunday: "series-sunday",
  Birthday: "series-birthday",
  Construction: "series-construction",
  Hippers: "series-hippers",
  Custom: "series-custom",
};
